In [9]:
import numpy as np

list = [10,20,30,40]

print(list)

arr = np.array(list)

print(type(arr))

[10, 20, 30, 40]
<class 'numpy.ndarray'>


In [12]:
#square the element using list and np

print([i**2 for i in list])
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print(arr**2)
print(type(arr**2))

#sum in numpy
print(np.sum(np_array))

[100, 400, 900, 1600]
[ 100  400  900 1600]
<class 'numpy.ndarray'>
15


In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

# Multiply elements
# For list, you need a loop:
py_result = [x * 2 for x in py_list]
np_result = np_array * 2  # Vectorized operation

print("List result:", py_result)
print("NumPy result:", np_result)

List result: [2, 4, 6, 8, 10]
NumPy result: [ 2  4  6  8 10]


In [60]:
#creating numpy array######

#using list

arr_1 = np.array([1,2,3,4,4])
print(arr_1)


#using arange like range

arr_2 = np.arange(1,10,1)
print(arr_2)

arr_2 = np.arange(1,10,2)
print(arr_2)


#using linspace
# vs range() or arange()?
#	•	range(1, 10, 2) or arange() → you give step size.
#	•	linspace(1, 10, 5) → you give how many numbers you want, and it calculates step size for you.

arr_3 = np.linspace(1,5,10)
print(arr_3)

#zero and ones

zero = np.zeros((2,3,3)) #rows,column
print(zero)

ones = np.ones((3,3))
print(ones)

[1 2 3 4 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element
print(arr[1:4])  # Slice elements 1 to 3

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print("Element at row 1, col 2:", matrix[0, 1])
print("First two rows:\n", matrix[:2, :])


print("shape",matrix.shape)
print("dimention",matrix.ndim)
#matrix[row,column]

print("row slicing")
print(matrix[0:2,:]) #-- #row slicing

print("column slicing")
print(matrix[:,0:2]) #- #column slicing

print(matrix[1,2])


10
[20 30 40]
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 2
First two rows:
 [[1 2 3]
 [4 5 6]]
shape (3, 3)
dimention 2
row slicing
[[1 2 3]
 [4 5 6]]
column slicing
[[1 2]
 [4 5]
 [7 8]]
6


In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

# Broadcasting example
arr3 = np.array([1, 2, 3])
print("Broadcasted add:", arr3 + 5)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Broadcasted add: [6 7 8]


In [59]:
arr = np.arange(1, 7)
print("Original:", arr)
print("Reshaped 2x3:\n", arr.reshape(2, 3)) #number should be even to reshape and that count of eleemnt should be there 2*3 6 elelents hould be there
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())

Original: [1 2 3 4 5 6]
Reshaped 2x3:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Mean: 3.5
Max: 6
