**Series in pandas**

In [14]:
import pandas as pd

data = pd.Series([1,2,3,4,5])
print(type(data))
print(data)

#series will have data with default numbered index from zero

data_2 = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(data_2)

#accesing data
print("accessing data")
print(data[0])
print(data[0:2])

print(data_2["a"])
print(data_2["a":"d"])

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
accessing data
1
0    1
1    2
dtype: int64
1
a    1
b    2
c    3
d    4
dtype: int64


**DATAFRAME in pandas**

In [25]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data,index= ["a","b","c"])
df.head()

Name  Age         City
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago

In [29]:
#Accessing Data in DataFrames

"""
df['column']: Access a column.
df.loc[row_label]: Access by label.
df.iloc[row_index]: Access by integer index.
"""
print(df["Age"])
print("*******")
print(df.loc["a"])
print(df.loc["b"]) ##local
print("********")
print(df.iloc[0]) ## like indexloc

a    25
b    30
c    35
Name: Age, dtype: int64
*******
Name       Alice
Age           25
City    New York
Name: a, dtype: object
Name            Bob
Age              30
City    Los Angeles
Name: b, dtype: object
********
Name       Alice
Age           25
City    New York
Name: a, dtype: object


In [33]:
df.head()
df.tail()
df.describe(include="all")

Name   Age      City
count       3   3.0         3
unique      3   NaN         3
top     Alice   NaN  New York
freq        1   NaN         1
mean      NaN  30.0       NaN
std       NaN   5.0       NaN
min       NaN  25.0       NaN
25%       NaN  27.5       NaN
50%       NaN  30.0       NaN
75%       NaN  32.5       NaN
max       NaN  35.0       NaN

In [37]:
#homework on numpy and pandas

import numpy as np

np_data = np.arange(1,21)
print(np_data)

print(np_data.reshape(4,5))
print(np_data.reshape(4,5).ndim)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2


In [41]:
data = {"Name":["sabari","mohana","kave"],"marks":[35,45,50],"grade":["C","B","A"]}

student  = pd.DataFrame(data)
print(student)

     Name  marks grade
0  sabari     35     C
1  mohana     45     B
2    kave     50     A


In [49]:
print(student.iloc[1,1])
print(student.loc[1][1])
student.describe()

45
45


/tmp/ipython-input-4155485266.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(student.loc[1][1])


marks
count   3.000000
mean   43.333333
std     7.637626
min    35.000000
25%    40.000000
50%    45.000000
75%    47.500000
max    50.000000